#! /bin/sh

# Wrapper for cvs, that retries seevral times in case of failure

# Usage:
#   cvs <module name>

CVS_RSH=ssh cvs -d:ext:bonniot@$CVS_SOURCEFORGE:/cvsroot/nice ${2:-export} \
    "${CVS_DATE:--rHEAD}" "$1"
