#! /bin/sh

CVSROOT=:pserver:anoncvs@oss.software.ibm.com:/usr/cvs/jikes
export CVSROOT

echo "Getting JACKS from CVS"

if grep 'anoncvs@oss.software.ibm.com' $HOME/.cvspass >/dev/null 2>&1; then
  true
else
  echo "Password is 'anoncvs'"
  cvs login
fi
cvs -z 3 checkout -P jacks
