#! /bin/sh

echo > dateBuild.nice
echo "package nice.tools.compiler;" >> dateBuild.nice
echo "var String versionNumber = \"$1\";" >> dateBuild.nice
echo "var String buildDate = \""`date -u +"%Y.%m.%d, %T %Z"`"\";" >> dateBuild.nice
