#! /bin/sh

if [ -z "$3" ]; then
  version="$1"
else
  version="$1 $3"
fi

javaVersion="$2"

date="`date -u +'%Y.%m.%d, %T %Z'`"

echo > dateBuild.nice
echo "package nice.tools.compiler;" >> dateBuild.nice
echo "public let String versionNumber = \"$version\";" >> dateBuild.nice
echo "public let String buildDate = \"$date\";" >> dateBuild.nice
echo "public let String javaVersion = \"$javaVersion\";" >> dateBuild.nice


echo "Main-Class: nice.tools.compiler.console.fun
Implementation-Title: Nice Compiler
Implementation-Version: $version
Implementation-Vendor: Daniel Bonniot
Implementation-URL: http://nice.sourceforge.net
Build-Id: Nice compiler version $version (build $date)
" > ./Manifest
