#! /bin/sh

# This script must be run after each change to coreJava.code
# to produce the Java and Nice versions of the test package

if newer coreJava.nice.template ok.out; then
    sed -e /BODY/"r coreJava.code" -e /BODY/d coreJava.nice.template \
	> coreJava.nice
fi

if newer coreJava.java.template ok.out; then
    sed -e /BODY/"r coreJava.code" -e /BODY/d coreJava.java.template \
	> coreJava.java
fi

if newer coreJava.code ok.out; then
    CLASSPATH=.:$CLASSPATH
    export CLASSPATH

    if javac coreJava.java; then
	java coreJava > ok.out
	exit $?
    else
	exit $?
    fi
fi

