#! /bin/sh

# This script must be run after each change to coreJava.code
# to produce the Java and Nice versions of the test package

if newer ok.out coreJava.code; then
  echo "(skipped)"
  exit
fi

sed -e /BODY/"r coreJava.code" -e /BODY/d coreJava.java.template \
	> coreJava.java
sed -e /BODY/"r coreJava.code" -e /BODY/d coreJava.nice.template \
	> coreJava.nice

if javac coreJava.java; then
  java coreJava > ok.out
  exit $?
else
  exit $?
fi

