#! /bin/sh

# This script must be run after each change to coreJava.code
# to produce the Java and Nice versions of the test package

if newer Nop.class Nop.java; then
  echo "(skipped)"
  exit
fi

CLASSPATH=$NICE_TOP/classes:$CLASSPATH
export CLASSPATH

javac -classpath $NICE_TOP/classes Nop.java
