#! /bin/sh

# This script must be run after each change to coreJava.code
# to produce the Java and Nice versions of the test package

if newer Nop.class Nop.java; then
  if newer Fields.class Fields.java; then
    echo "(skipped)"
    exit
  fi
fi

CLASSPATH=$NICE_TOP/classes:$CLASSPATH
export CLASSPATH

javac Nop.java Fields.java
